# Generated by Django 3.1 on 2020-08-17 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200817_0643'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='listings',
            new_name='listing',
        ),
    ]
