# Generated by Django 3.1 on 2020-08-17 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='by',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 17, 8, 31, 5, 370933)),
        ),
    ]
