# Generated by Django 3.1 on 2020-08-17 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20200817_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='changed',
            field=models.TextField(default='False'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 17, 10, 49, 25, 501454)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 17, 10, 49, 25, 500456)),
        ),
    ]
