# Generated by Django 3.1 on 2020-08-18 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_auto_20200818_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 18, 13, 32, 2, 370495)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 18, 13, 32, 2, 370495)),
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='listing_id',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='listing_id',
            field=models.ManyToManyField(to='auctions.listing'),
        ),
    ]
