# Generated by Django 3.1 on 2020-08-17 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200817_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('listing_id', models.IntegerField(blank=True, null=True)),
                ('bid', models.FloatField()),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 8, 17, 9, 57, 50, 313849))),
            ],
        ),
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 17, 9, 57, 50, 312854)),
        ),
    ]
