# Generated by Django 3.1 on 2020-08-17 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20200817_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('listing_id', models.IntegerField(blank=True, null=True)),
                ('bid', models.FloatField()),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 8, 17, 10, 0, 20, 800232))),
            ],
        ),
        migrations.DeleteModel(
            name='Biding',
        ),
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 17, 10, 0, 20, 799238)),
        ),
    ]
