# Generated by Django 3.1 on 2020-08-17 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20200817_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='active',
            field=models.TextField(default='False'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 17, 11, 1, 4, 298845)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 17, 11, 1, 4, 297848)),
        ),
    ]
