# Generated by Django 3.1 on 2020-08-17 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20200817_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 17, 12, 21, 0, 79001)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='active',
            field=models.TextField(default='True'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 17, 12, 21, 0, 78001)),
        ),
    ]
