# Generated by Django 3.1 on 2020-08-18 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0029_auto_20200818_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 18, 13, 34, 38, 217909)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 18, 13, 34, 38, 217909)),
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='listing_id',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='listing_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
