# Generated by Django 3.1 on 2020-08-19 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_auto_20200819_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 6, 57, 2, 30303)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 6, 57, 2, 29308)),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='user',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
