# Generated by Django 3.1 on 2020-08-19 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0042_auto_20200819_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 9, 50, 0, 51893)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 9, 50, 0, 50896)),
        ),
    ]
